image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - mandoc
  - scdoc
  - hut
sources:
  - https://git.sr.ht/~whynothugo/darkman
tasks:
  - site: |
      cd darkman
      make site.tar.gz
  - publish: |
      cd darkman
      hut pages publish -d darkman.whynothugo.nl site.tar.gz
