lint:
  image: golangci/golangci-lint:v1.41.1
  script:
    - golangci-lint run -v

test:
  image: golang:1.16
  script:
    - go test

build:
  image: golang:1.16
  script:
    - go build
  artifacts:
    paths:
      - darkman
