lint:
  image: golangci/golangci-lint:v1.45.2
  script:
    - golangci-lint run -v

test:
  image: golang:1.18
  script:
    - go test

build:
  image: golang:1.18
  script:
    - go build
  artifacts:
    paths:
      - darkman
